### ISSUE TITLE
Support global arguments

### ISSUE THREAD

**Issue by justinfagnani** [75lb/command-line-commands#3]
We'd like to handle flags like `--version` and `--help` without requiring a command name.

Something like this would be nice:

``` javascript

let cli = commandLineCommands([
  { name: 'help' },
  { name: 'run', definitions: [ { name: 'why', type: String } ] },
], {
  globalDefinitions: [
    { name: 'version', type: Boolean },
  ],
});

let command = cli.parse();
if (command.name == null && command.options.version) {
  printVersion();
}
```

**Comment by 75lb** [comment]
yep, i'm on the case. This feature will land soon, cheers!

**Comment by 75lb** [comment]
the work for this fix is done, just need to write the docs and do a release (later today).. watch this space.

**Comment by 75lb** [comment]
fixed in the v1.0.0 release.. please let me know if the docs are unclear or if you have any more issues..

**Comment by 75lb** [comment]
i plan to do more work on the [advanced example](https://github.com/75lb/command-line-commands/blob/master/example/advanced/git.js) tomorrow but the main library code is ready for use.. 

i'm also working on v3 of command-line-usage and command-line-args.. nows a good time to feedback on those libraries, if you have any thoughts.. 

cheers!

**Comment by justinfagnani** [comment]
I'm a bit confused by the docs. Did you remove the ability to specify arguments altogether?

**Comment by 75lb** [comment]
yes, forget the previous API - it changed.. now, this module's only job is to parse and extract the command from `process.argv`.. i reduced the scope of this module, removing the hard deps on command-line-args and command-line-usage.. now, they are each separate modules, working in isolation or together.. it means you can use this module with any option-parser.

with the `commandLineCommands()` output, you can make a decision what to do, depending on the command received.. for further option-parsing, pass the `argv` you get back from `commandLineCommands()` into `commandLineArgs.parse()`.. have a look at the [examples](https://github.com/75lb/command-line-commands#examples), do they help?

**Comment by 75lb** [comment]
i updated the README a bit, hopefully it makes sense now.. 

i had a very quick look at `polymer-cli`.. didn't have much time, but here's a rough example of how you might use clc v1:

``` js
logger.debug('running...');
const commandLineArgs = require('command-line-args')
const commandLineCommands = require('command-line-commands')

const { command, argv } = commandLineCommands(null, 'help', 'init', 'lint', 'test', 'build', 'serve')

// no command passed
if (command === null) {
  const cli = commandLineArgs([
    { name: 'version', type: Boolean },
    { name: 'help', type: Boolean }
  ])
  const options = cli.parse(argv)

  if (options.version) {
    console.log(require('../package.json').version);
  }

// init
} else if (command === 'init') {
  const cli = commandLineArgs([
    {
      name: 'name',
      description: 'The template name to use to initialize the project',
      type: String,
      defaultOption: true,
    }
  ])
  const options = cli.parse(argv) 
  // load and run the polymer init command here, as usual
}

// etc
```
